# Generated by Django 5.0.7 on 2024-07-24 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_userauth_is_active_userauth_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
    ]
