# Generated by Django 5.0.7 on 2024-07-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_userauth_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
