# Generated by Django 5.0.7 on 2024-07-26 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
