# Generated by Django 5.0.7 on 2024-07-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_task_due_date_alter_task_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='current_status',
            field=models.IntegerField(choices=[(0, 'In Progress'), (1, 'Pending'), (2, 'Completed'), (3, 'Archived')], default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.BooleanField(choices=[(0, 'Low'), (1, 'High')], default=True),
        ),
    ]
